### ISSUE TITLE
Use media function keys

### ISSUE THREAD

**Issue by Gprime5** [Aayush9029/Rifi#2]
https://pyautogui.readthedocs.io/en/latest/keyboard.html#keyboard-keys

You can use pyautogui to press function keys like "playpause", "nexttrack", "volumeup", etc which doesn't need mouse focus to effect the media.

**Comment by Aayush9029** [comment]
I totally agree on this however web player like YouTube does't seem to support media keys. I will add this to my to do list and try to figure out a way to use both arrow and media control keys.

**Comment by kvosbur** [comment]
Still using media keys for controlling volume by doing global volume instead of player volume can always be used instead of needing to have player in focus. Also this would allow for adding a mute button to the online player.

**Comment by Aayush9029** [comment]
For sure I’ll change it so that it use media keys instead of keyboard presses. 

Do you think it will be a good idea to add an extra ui which gives user system volume and media controls instead of using the same ui?

**Comment by kvosbur** [comment]
Personally I would be fine for overwriting the volume to use just system since I think that would be easier to control. For the left and right keys there is a difference between what the media keys do and what the arrow keys accomplish depending on the player. For these it might be worth to have separated out since it will depend on the situation for how they react.

**Comment by ThibaultNocchi** [comment]
YouTube has its own keys IIRC, like K (on my AZERTY) pauses or resumes.

**Comment by Aayush9029** [comment]
So I added couple of new buttons to test if pyautoggui's volume press works on macOS and it didn't seem to work at all.  I tried sending "volumedown, prevtrack, nexttrack, volumeup, volumemute" instead of standard up and down arrow despite playing music from Official music app none of the buttons worked. How ever I found a work around for changing volume

`from subprocess import call`
`call(["osascript -e 'set volume output volume 100'"], shell=True)`

*doing so allows python to change volume via python (through apple script)*

**About my device:**
- MacBook Pro with Touch Bar 
- Running Catalina 10.15.3 

If any one has access to macOs try sending "volumeup" instead of just "up" in the index.html file which is inside "PythonApp/templates" directory.

Can anyone confirm "volumemute" works on windows as well?

**Comment by kvosbur** [comment]
I am using windows 10 and can say that the volumeup, volumedown, volumemute, nexttrack, prevtrack all do what I would expect them to do as if I did the actual button presses. It seems like we are going to have to start detecting the user's OS and changing the corresponding actions accordingly.

**Comment by Aayush9029** [comment]
Agreed on that. Thanks a lot.

---
Here's a new layout I'm working on any thoughts?

<img width="376" alt="Screen Shot 2020-03-02 at 12 32 20 PM" src="https://user-images.githubusercontent.com/43297314/75701539-f8a01a00-5c81-11ea-8b6e-4ab8cf8652e7.png">
---

**Comment by Aayush9029** [comment]
Agreed.

**Comment by Aayush9029** [comment]
GUYS there seems to be an issue with manjaro as well media key doesn't seem to work like macOS can anyone confirm?

**Comment by kvosbur** [comment]
This just shows that we definitely need to setup the project to detect the OS and change the actions that occur depending on the OS. I can work on setting up the basics for this. Also if you can push the work you have currently done for your version 1.3 to a different branch than master it would be nice for us to more easily see the changes and run the same thing you are on our own machines.

**Comment by Aayush9029** [comment]
Will keep this mind for further changes. How’s v1.3 looking?

**Comment by kvosbur** [comment]
I haven't had much chance to try it out lately since I have been busy with life.

**Comment by Aayush9029** [comment]
Take your time.

**Comment by Aayush9029** [comment]
Media control seems to work on macOs *unix* and windows as expected however I've yet to look further into linux systems.
