### ISSUE TITLE
Why randomized ports instead of static.

### ISSUE THREAD

**Issue by kvosbur** [Aayush9029/Rifi#5]
I don't quite understand your logic behind using a randomized port number instead of using the same port number even single time. If you used the same port every time it would make it easier to access since you can make shortcuts on your phone or such to use the port every time instead of having to use the qr or type in a new port number. There shouldn't be any overlap with existing services by using a port in the range that you are currently using either.

**Comment by Aayush9029** [comment]
I thought it would add a little bit of security if people use this app outside of their home internet. Even though this will not "Protect" them from people other people accessing the web interface it might slow them down a little. I might change the port from random to static as it will enable it to be a a lot accessible and easy to use and since any network mapper can easily find open ports randomizing the port might be redundant way of "securing" the app. Thanks I'll change it to static
